# Generated by Django 3.2.6 on 2022-12-28 13:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrenheit_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_acct_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('prof_pic', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('apps_following', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('profile_status', models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='app.Fahrenheit_Profile')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_fahrenheit_profile',
            },
        ),
    ]
