# Generated by Django 3.2.6 on 2023-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecstastream_playlist_data',
            name='media_type',
            field=models.IntegerField(blank=True, choices=[(0, 'movie'), (1, 'tv')], null=True),
        ),
    ]
