# Generated by Django 3.2.6 on 2023-01-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_app_following',
            name='mute_notifications',
            field=models.BooleanField(choices=[(1, 'No'), (0, 'Yes')], default=1),
        ),
    ]
