# Generated by Django 3.2.6 on 2023-01-01 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrenheit_app_list',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_app_following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followuing_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
