# Generated by Django 3.2.6 on 2022-12-28 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fahrenheit_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahrenheit_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='fahrenheit_profile',
            name='user_acct_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
