# Generated by Django 3.2.6 on 2023-01-01 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230101_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_app_following',
            name='following_app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='app.fahrenheit_app_list'),
        ),
        migrations.AlterField(
            model_name='user_app_following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_following',
            name='following_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
