# Generated by Django 3.2.6 on 2023-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230118_1034'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fahrenheit_app_list',
            constraint=models.UniqueConstraint(fields=('app_name',), name='app_id_constraint'),
        ),
    ]
