# Generated by Django 3.2.12 on 2022-12-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_fahrenheituser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrenheituser',
            name='profile_status',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0),
        ),
        migrations.AddField(
            model_name='fahrenheituser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Restricted')], default=0),
        ),
        migrations.CreateModel(
            name='EcstaStreamProfile',
            fields=[
                ('ec_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Restricted')], default=0)),
                ('profile_status', models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='app.EcstaStreamProfile')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcstaStreamPlaylist',
            fields=[
                ('ec_playlist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=150, null=True)),
                ('cover_img', models.ImageField(default='defaultplaylist.png', null=True, upload_to='cover_images')),
                ('comments', models.TextField(null=True)),
                ('comments_on', models.BooleanField(default=True)),
                ('status', models.BooleanField(choices=[(0, 'Open'), (1, 'Restricted')], default=0)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist_follows', models.ManyToManyField(default=None, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('share_list', models.ManyToManyField(default=None, related_name='sharing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='ecstastreamplaylist',
            constraint=models.UniqueConstraint(fields=('created_by', 'ec_playlist_id', 'title'), name='user_playlist_constraint'),
        ),
    ]
