# Generated by Django 3.2.6 on 2023-01-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230112_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_app_following',
            options={'managed': False, 'ordering': ['date_added']},
        ),
    ]
