# Generated by Django 3.2.6 on 2023-02-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ecstastream_playlist_data_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcstaStream_Watchlist',
            fields=[
                ('watchlist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=True)),
                ('status', models.BooleanField(choices=[(0, 'Open'), (1, 'Restricted')], default=0)),
                ('wl_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='app.ecstastreamprofile')),
            ],
            options={
                'verbose_name_plural': 'Watchlists',
                'ordering': ['-created_on'],
                'unique_together': {('wl_user_id',)},
            },
        ),
        migrations.CreateModel(
            name='EcstaStream_Favorites',
            fields=[
                ('favorite_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(default=True)),
                ('status', models.BooleanField(choices=[(0, 'Open'), (1, 'Restricted')], default=0)),
                ('favs_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favs', to='app.ecstastreamprofile')),
            ],
            options={
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_on'],
                'unique_together': {('favs_user_id',)},
            },
        ),
        migrations.CreateModel(
            name='EC_Watchlist_Data',
            fields=[
                ('wl_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wl_mov_show_id', models.IntegerField()),
                ('wl_date_added', models.DateTimeField(auto_now=True)),
                ('media_type', models.IntegerField(blank=True, choices=[(0, 'movie'), (1, 'tv')], null=True)),
                ('watchlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_id', to='app.ecstastream_watchlist')),
                ('wl_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to='app.ecstastreamprofile')),
            ],
            options={
                'verbose_name_plural': 'Ecstastream Watchlist Data',
                'ordering': ['-wl_date_added'],
            },
        ),
        migrations.CreateModel(
            name='EC_Favorites_Data',
            fields=[
                ('fav_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fav_mov_show_id', models.IntegerField()),
                ('fav_date_added', models.DateTimeField(auto_now=True)),
                ('media_type', models.IntegerField(blank=True, choices=[(0, 'movie'), (1, 'tv')], null=True)),
                ('fav_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs_user', to='app.ecstastreamprofile')),
                ('favorites_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_id', to='app.ecstastream_favorites')),
            ],
            options={
                'verbose_name_plural': 'Ecstastream Favorites Data',
                'ordering': ['-fav_date_added'],
            },
        ),
        migrations.AddConstraint(
            model_name='ec_watchlist_data',
            constraint=models.UniqueConstraint(fields=('watchlist_id', 'wl_mov_show_id', 'media_type'), name='watchlist_data_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='ec_watchlist_data',
            unique_together={('watchlist_id', 'wl_mov_show_id', 'media_type')},
        ),
        migrations.AddConstraint(
            model_name='ec_favorites_data',
            constraint=models.UniqueConstraint(fields=('favorites_id', 'fav_mov_show_id', 'media_type'), name='favs_data_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='ec_favorites_data',
            unique_together={('favorites_id', 'fav_mov_show_id', 'media_type')},
        ),
    ]
