# Generated by Django 3.2.12 on 2022-12-14 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fahrenheituser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fahrenheituser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fahrenheituser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
