# Generated by Django 3.2.6 on 2023-01-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ecstastreamprofile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecstastreamplaylist',
            name='comments_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ecstastreamplaylist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='app.ecstastreamprofile'),
        ),
    ]
