# Generated by Django 3.2.6 on 2023-01-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_app_following_mute_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_app_following',
            name='mute_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
