# Generated by Django 3.2.6 on 2023-01-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fahrenheit_app_list_app_id_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecstastream_playlists_following',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
