# Generated by Django 3.2.12 on 2022-12-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221214_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fahrenheituser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fahrenheituser',
            name='username',
        ),
    ]
