# Generated by Django 3.2.6 on 2023-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_app_following_mute_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_app_following',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
