# Generated by Django 3.2.6 on 2023-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230124_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcstaStream_User_Steaming_List',
            new_name='EcstaStream_User_Streaming_List',
        ),
        migrations.AlterModelOptions(
            name='ecstastream_playlist_data',
            options={'ordering': ['-pl_date_added'], 'verbose_name_plural': 'Ecstastream Playlist Data'},
        ),
        migrations.AlterModelOptions(
            name='ecstastream_playlists_following',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'Ecstastream Playlist Followers'},
        ),
        migrations.AlterModelOptions(
            name='ecstastreamplaylist',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Ecstastream Playlists'},
        ),
        migrations.AlterModelOptions(
            name='ecstastreamprofile',
            options={'verbose_name_plural': 'Ecstastream Profiles'},
        ),
        migrations.AlterModelOptions(
            name='fahrenheit_app_list',
            options={'verbose_name_plural': 'Fahrenheit Apps'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': False, 'verbose_name_plural': 'Ecstastream Genres'},
        ),
        migrations.AlterModelOptions(
            name='streamingservices',
            options={'managed': False, 'verbose_name_plural': 'Ecstastream Streaming Services'},
        ),
        migrations.AlterModelOptions(
            name='streamingurls',
            options={'managed': False, 'verbose_name_plural': 'Ecstastream Streaming URLs'},
        ),
        migrations.AlterModelOptions(
            name='user_app_following',
            options={'ordering': ['date_added'], 'verbose_name_plural': 'Fahrenheit App Followers'},
        ),
        migrations.AlterUniqueTogether(
            name='ecstastream_user_streaming_list',
            unique_together={('user_streaming', 'streaming_id')},
        ),
        migrations.AlterUniqueTogether(
            name='ecstastreamprofile',
            unique_together={('user_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='user_app_following',
            unique_together={('following_app_id', 'user')},
        ),
    ]
