# Generated by Django 3.2.6 on 2023-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_app_following_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_app_following',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterField(
            model_name='user_app_following',
            name='mute_notifications',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
