# Generated by Django 3.2.6 on 2023-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230124_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow_request',
            options={'verbose_name_plural': 'Fahrenheit Follower Requests'},
        ),
        migrations.AlterModelOptions(
            name='user_following',
            options={'verbose_name_plural': 'Fahrenheit Followers'},
        ),
        migrations.AddField(
            model_name='ecstastreamprofile',
            name='streaming_services',
            field=models.ManyToManyField(related_name='user_streaming_services', to='app.StreamingServices'),
        ),
    ]
