# Generated by Django 3.2.12 on 2022-12-14 23:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221214_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrenheituser',
            name='apps_following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
